### ISSUE TITLE
add data-alpheios-ignore="all" to panel menus and contents

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#41]
we need to deactivate alpheios on the panel contents and menu items.

**Comment by balmas** [comment]
(this issue was probably made more visible by the setting of the minimum duration for the touch events to 0)

**Comment by kirlat** [comment]
We can't deactivate it completely because we need to listen to swipe on a panel header. However, I added special data attributes that allow to deactivate certain custom pointer events selectively.

It had a long tap event deactivated within a panel. It was listening for swipe in menus, but never identified swipe because its conditions were not met. I fixed that with 0a8a21e3f8ebab6627f9a4bf9cc9ad8e695cf134. It will not listen for swipe in menu at all now.

I think many messages inside HTML panel were confusing: it was reporting events that never went into custom pointer processing pipeline. I tried to fix that. It will report less events and, I hope, will do that in a cleaner way.

**Comment by balmas** [comment]
ok. it seems to be working much better right now.

**Comment by balmas** [comment]
still not working right for panel buttons when the panel buttons appear across the top rather than in the menu. On android it's fine but on iOS it's causing lookups

**Comment by balmas** [comment]
actually it's fine in the dev build, so I think the problem is just the prod build update issue caused by #46

**Comment by balmas** [comment]
changed my mind again ... it's still flaky in the dev environment -- it's inconsistent but not quite right.

**Comment by balmas** [comment]
interestingly, when verbose is on and the html console is showing I can't reproduce it. But when verbose is on and the html console IS showing, it occurs (and i can't debug).
With the console showing, I get Swipe (not completed) messages in the console when it works the way it should.

**Comment by balmas** [comment]
Couldn't we change the the getSelectedText method in app-process to just return if the selected element has an alpheios-ignore data attribute? or one of the alph-exclude-* attributes?
